language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t michmoca/projectreact -f Dockerfile.dev

script:
  - docker run -e CI=true michmoca/projectreact npm run test -- --coverage

deploy:
  provider: elasticbeanstalk